/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormIngreso.java
 *
 * Created on 15/11/2011, 06:39:22 PM
 */
package analizadorlr;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author juanda
 */
public class FormIngreso extends javax.swing.JFrame {
    //char variables[];
    char simbolos[];
    String var = "S";
    String tabla [][];
    String MatrizFinal[][];
    // matriz ArregloVariables = new matriz();
     Vector vectorVariables = new Vector();
     Vector vectorSimbolos = new Vector();
     Vector vectorProducciones =  new Vector();
     Vector vectorOrdenados = new Vector();//Vector para almacenar las producciones en el mismo orden en que aparecen los simblos.
     Vector vectorTabla = new Vector();//Vector de vectores para almacenar la tabl completa
     int tamanoVectorSimbolos= vectorSimbolos.size();
     int tamanoVectorVariables;
     int numvariable = 0;
     int produccion = 0;
    public int numproducciones=0;

//     public void almacenarDatosTabla (Vector vectorAlmacenar){
//       vectorTabla.add(vectorAlmacenar);
//     }

    /** Creates new form FormIngreso */
    public FormIngreso() {
        initComponents();
        vectorVariables.add("S");
       String a = (String)vectorVariables.elementAt(0);
       vectorSimbolos.add(0,"");
       LabelVariable.setText(a);

    }
    
    public void repetidosVariables(Vector cadena){
        boolean repetido=false;
           for(int j=0;j<cadena.size();j++){
               if (vectorVariables.contains(cadena.elementAt(j))){
                   repetido=true;
               }
               else
                   vectorVariables.add(cadena.elementAt(j));
    }
    }


   public void repetidosSimbolos(Vector cadena){
        boolean repetido=false;
           for(int j=0;j<cadena.size();j++){
               if (vectorSimbolos.contains(cadena.elementAt(j))){
                   repetido=true;
               }
               else
                   vectorSimbolos.add(cadena.elementAt(j));
    }
    }

   public void copiarMatrizFinal (String[][] tabla, int fila, int tamano){
      for (int i =0; i<tamano;i++){
          MatrizFinal[fila][i]=tabla[0][i];
      }
   }

//    public void copiarVariables(char[] variables, int tamano){ //tamano infica el siguiente cuadro en blanco para agregar las variables y simbolos
//        char a;
//        int longitudvector = variables.length;
//        for (int i = tamano; i<longitudvector;i++){
//            this.variables[i]=variables[i];
//        }

//    }

    public void setVariable(){
        tamanoVectorVariables = vectorVariables.size();
        if (numvariable<tamanoVectorVariables){
        String letra = vectorVariables.elementAt(numvariable).toString();
        if (letra=="S"){
            numvariable++;
            letra = vectorVariables.elementAt(numvariable).toString();
            }
        LabelVariable.setText(letra);
        //numvariable++;
    }
        else{
            ButtonNuevaProduccion.setEnabled(false);
            BtnSiguienteVariable.setEnabled(false);
            ButtonNext.setEnabled(true);
        }
    }

    public String getVar() {
        return var;
    }

    public void setVar(String var) {
        this.var = var;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelVariable = new javax.swing.JLabel();
        TextFieldProduccion = new javax.swing.JTextField();
        ButtonNuevaProduccion = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        ButtonNext = new javax.swing.JButton();
        BtnSiguienteVariable = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Producciones de   :");

        ButtonNuevaProduccion.setText("Agregar produccion");
        ButtonNuevaProduccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonNuevaProduccionMouseClicked(evt);
            }
        });

        ButtonCancel.setText("Cancelar");
        ButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCancelMouseClicked(evt);
            }
        });

        ButtonNext.setText("Siguiente");
        ButtonNext.setEnabled(false);
        ButtonNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonNextMouseClicked(evt);
            }
        });

        BtnSiguienteVariable.setText("Siguiente variable");
        BtnSiguienteVariable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSiguienteVariableMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel2.setText("* Lambda-->$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonNuevaProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnSiguienteVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(ButtonNuevaProduccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSiguienteVariable)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(LabelVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNext)
                    .addComponent(ButtonCancel))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCancelMouseClicked
    System.exit(0);        // Salir de la aplicacion
    }//GEN-LAST:event_ButtonCancelMouseClicked

    private void ButtonNuevaProduccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNuevaProduccionMouseClicked

        String varchar = TextFieldProduccion.getText();//Obtener el texto ingresado por el usuario
        validador validacion = new validador();//Crea un objeto de tipo validador
        boolean correcto = validacion.validar(varchar);//envia la palabra 'varchar' al objeto validacion
        boolean acepta = validacion.variables(varchar);
        boolean repite = validacion.repite(varchar);
        if (correcto == true && acepta== true && repite==false){ //si el validador devuelve true, la evaluacion sintactica fue correcta
            if (produccion==0){
            vectorProducciones.add(vectorVariables.elementAt(numvariable));
            produccion = 1;
            }
            vectorProducciones.add(varchar);
            repetidosSimbolos(validacion.getSimbolos());
            repetidosVariables(validacion.getVariables());
            TextFieldProduccion.setText(null);//Limpia el cuadro de texto para que el usuario
                                                //ingrese una nueva produccion.
            //numvariable++;
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Verifique e ingrese "
                                             + "nuevamente la produccion", "ERROR!", JOptionPane.ERROR_MESSAGE);
            TextFieldProduccion.setText(null);
           
        }
    }//GEN-LAST:event_ButtonNuevaProduccionMouseClicked

    private void ButtonNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonNextMouseClicked
        
        Cadena ventanaCadena = new Cadena();
        ventanaCadena.setTablaRecibida(MatrizFinal);
        ventanaCadena.setNumerocolumnas(tamanoVectorVariables);
        ventanaCadena.setNumerofilas(tamanoVectorSimbolos);
        ventanaCadena.main();
        this.setVisible(false);
        //**LLAMAR A DOS METODOS PARA QUE ORGANICEN LOS DATOS EN LOS VECTORES**
        //organizar organiceVector = new organizar();
        
        //vectorOrdenados=organiceVector.ordenar(vectorTabla, vectorSimbolos);
//
//        matriz armarTabla = new matriz();
//        tamanoVectorSimbolos=vectorSimbolos.size();
//        tamanoVectorVariables=vectorVariables.size();
//        //if (numproducciones==1){
//        String tabla[][]=armarTabla.construirTabla(vectorSimbolos, vectorTabla,tamanoVectorSimbolos,tamanoVectorVariables);
//        TablaAnalisis tablaAnalizador = new TablaAnalisis();
//        tablaAnalizador.setMatriz(tabla);
//        String[] st =new String[vectorSimbolos.size()];
//        vectorSimbolos.toArray( st );
//        tablaAnalizador.setSimbolos(st);
        //TablaAnalisis.main();

    }//GEN-LAST:event_ButtonNextMouseClicked

    private void BtnSiguienteVariableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSiguienteVariableMouseClicked
        numproducciones++;
        numvariable++;
        setVariable();
        vectorTabla.add(vectorProducciones);
        matriz almacenarDatosTabla = new matriz();
        if(numproducciones==1){
        vectorSimbolos.add("$");
        }
        tamanoVectorSimbolos=vectorSimbolos.size();
        tamanoVectorVariables=vectorVariables.size();
        tabla=almacenarDatosTabla.construirTabla(vectorSimbolos,vectorProducciones,tamanoVectorSimbolos,1);
        if(numproducciones==1){
            MatrizFinal=new String[tamanoVectorVariables][tamanoVectorSimbolos+3];
            copiarMatrizFinal(tabla, 0,tamanoVectorSimbolos);
        }
        copiarMatrizFinal(tabla, 1,tamanoVectorSimbolos);
        vectorProducciones.clear();
        produccion=0;
    }//GEN-LAST:event_BtnSiguienteVariableMouseClicked

    /**
    * @param args the command line arguments=
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSiguienteVariable;
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonNext;
    private javax.swing.JButton ButtonNuevaProduccion;
    private javax.swing.JLabel LabelVariable;
    private javax.swing.JTextField TextFieldProduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
